apiVersion: apps/v1
kind: Deployment
metadata:
  name: trade-service
  namespace: confighubplaceholder  # Resolved via Link to namespace unit
  labels:
    app: trade-service
    component: trading-engine
spec:
  replicas: 3
  selector:
    matchLabels:
      app: trade-service
  template:
    metadata:
      labels:
        app: trade-service
        component: trading-engine
    spec:
      containers:
      - name: trade-service
        image: ghcr.io/finos/traderx/trade-service:latest
        ports:
        - containerPort: 8081
          name: http
        - containerPort: 9090
          name: metrics
        env:
        - name: SERVICE_NAME
          value: "trade-service"
        - name: REFERENCE_DATA_URL
          value: "http://reference-data:8080"
        - name: TRADING_ALGORITHM
          value: "v1"
        - name: CIRCUIT_BREAKER
          value: "false"
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: trade-service
  namespace: confighubplaceholder  # Resolved via Link to namespace unit
  labels:
    app: trade-service
spec:
  selector:
    app: trade-service
  ports:
  - port: 8081
    targetPort: 8081
    name: http
  - port: 9090
    targetPort: 9090
    name: metrics
  type: ClusterIP
