#!/bin/bash
# Stage 7: Emergency Bypass - Lateral promotion
set -e

echo "🚨 Stage 7: Emergency Bypass (Lateral Promotion)"
echo "================================================"
echo ""

./setup-structure 7
./deploy 7

echo ""
echo "✅ Stage 7 Complete!"
echo ""
echo "🎯 POWER FEATURE: Emergency Bypass"
echo ""
echo "Scenario:"
echo "  Normal flow: dev → staging → us → eu → asia"
echo "  Emergency: Critical bug found in EU at market open!"
echo "  Need: Fix in Asia within 2 hours (can't wait for US testing)"
echo ""
echo "Solution: Lateral promotion"
echo ""
echo "  # Emergency fix in EU"
echo "  cub run set-env-var --env-var CIRCUIT_BREAKER=true \\"
echo "    --unit trade-service --space traderx-prod-eu"
echo ""
echo "  # Push directly to Asia (bypass US!)"
echo "  cub unit update trade-service --space traderx-prod-asia \\"
echo "    --merge-unit traderx-prod-eu/trade-service"
echo ""
echo "  # Backfill US later when market closed"
echo "  cub unit update trade-service --space traderx-prod-us \\"
echo "    --merge-unit traderx-prod-eu/trade-service"
echo ""
echo "Flow:"
echo "  Normal:   dev → staging → us → eu → asia"
echo "  Emergency:                 eu → asia  (Skip US!)"
echo "  Backfill:                  eu → us    (Later)"
echo ""
echo "🎉 TUTORIAL COMPLETE!"
echo ""
echo "You've learned:"
echo "  ✓ Spaces and units"
echo "  ✓ Environment management"
echo "  ✓ Regional customization"
echo "  ✓ Push-upgrade pattern"
echo "  ✓ Find and fix"
echo "  ✓ Atomic updates"
echo "  ✓ Emergency bypass"
echo ""
echo "Next: Build your own DevOps automation!"
